import type { Metadata } from 'next'
import { TemplateHeader } from '@/app/component/templateHeader'
import { TemplateFooter } from '@/app/component/templateFooter'
import { useState } from 'react'
// import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <TemplateHeader title="todo header" />
      <main>{children}</main>
      <TemplateFooter title="todo footer" />
    </>
  )
}
